services:
  backend:
    build:
      context: .
      dockerfile: container/backend.dev.dockerfile
    volumes:
      - ./src/backend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./src/backend/.env
    networks:
      - development

  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./src/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - development

volumes:
  frontend_node_modules:

networks:
  development:
    name: r2manager-network-dev
    driver: bridge
